service:
  name: auction-service

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: ap-south-1

  environment:
    CLIENT_ID: '2jr56qs4jaf6gkkkeuaoit3rgc'
    AUCTIONS_TABLE_NAME: ${self:custom.AuctionsTable.name}
  iamRoleStatements:
    - ${file(iam/AuctionsTableIAM.yaml):AuctionsTableIAM}
    - Effect: 'Allow'
      Action:
        - 'ses:*'
      Resource:
        - '*'

resources:
  Resources:
    AuctionsTable: ${file(resources/AuctionsTable.yaml):AuctionsTable}

functions:
  createNewUser:
    handler: src/handlers/createNewUser.handler
    events:
      - http:
          method: POST
          path: /user
          cors: true
  sendConfirmationCode:
    handler: src/handlers/sendConfirmationCode.handler
    events:
      - cognitoUserPool:
          pool: 'EC-Newsletter-Subscription'
          trigger: CustomMessage
          existing: true

  confirmNewUser:
    handler: src/handlers/confirmNewUser.handler
    events:
      - http:
          method: POST
          path: /confirmuser
          cors: true
  createAuction:
    handler: src/handlers/createAuction.handler
    events:
      - http:
          method: POST
          path: /auction
          cors: true
  getAuctions:
    handler: src/handlers/getAuctions.handler
    events:
      - http:
          method: GET
          path: /auctions
          cors: true
  getAuction:
    handler: src/handlers/getAuction.handler
    events:
      - http:
          method: GET
          path: /auction/{id}
          cors: true
  placeBid:
    handler: src/handlers/placeBid.handler
    events:
      - http:
          method: PATCH
          path: auction/{id}/bid
          cors: true
  processAuctions:
    handler: src/handlers/processAuctions.handler
    # events:
    #   - schedule: rate(1 minute)
  sendRemainderDaily:
    handler: src/handlers/sendRemainderDaily.handler
    events:
      # - schedule: rate(1 day)

custom:
  AuctionsTable:
    name: !Ref AuctionsTable
    arn: !GetAtt AuctionsTable.Arn
  bundel:
    linting: false
  # copyFiles: # Copy any additional files to the generated package
  #   - from: 'src/lib/mail.html' # Where the files are currently
  #     to: './html/' # Where in the package should they go
